### ISSUE TITLE
Issue with P2xi function

### ISSUE THREAD

**Issue by franlane94** [eelregit/mcfit#4]
![Figure_1](https://user-images.githubusercontent.com/38043525/55198499-221d0f80-51ae-11e9-8909-e0249d6e3a44.png)
[correlation_function.pdf](https://github.com/eelregit/mcfit/files/3020447/correlation_function.pdf)

Hi,

I downloaded and installed the code a few weeks ago and it worked great and produced the PDF figure attached using the P2xi function. This week however I had to reinstall the code and now when I use the P2xi function on exactly the same power spectrum and k values I get the PNG image which doesn't look right. 

I don't think that it is a problem with the power spectrum/k values because they are from the exact same numpy array as was used before.

Thanks

**Comment by eelregit** [comment]
Hi Fran,

I changed two default options (`lowring` and `extrap`) of the package,
because I noticed a few users had assumed differently from what the package
was doing.

The previous `extrap=True` default is better for theoretical applications,
like what you are doing.
So could you try
r, xi = P2xi(k)(P, extrap=True)
and see if that solve the problem?

Otherwise, also try
r, xi = P2xi(k, lowring=True)(P)
and this finds the best r-array for you.

To use the previous defaults,
r, xi = P2xi(k, lowring=True)(P, extrap=True)

Let me know if this helps. Thanks!
Yin

**Comment by eelregit** [comment]
Closing this now. @franlane94 You can reopen it if the above options don't work for you.
